[project]
name = "compsoft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "glfw>=2.10.0",
    "pyopengl>=3.1.10",
]

[build-system]
requires = ["pdm-backend>=2.4.9"]
build-backend = "pdm.backend"

[tool.setuptools]
py-modules = []

[tool.uv]
link-mode = "copy"
default-groups = []

[tool.uv.workspace]
members = ["."]

[tool.uv.sources]
lightshow = { workspace = true }

[dependency-groups]
dev = [
    "isort>=8.0.1",
    "pre-commit>=4.6.0",
    "ruff>=0.15.17",
    "ty>=0.0.49",
]

[project.scripts]
compsoft = "compsoft.__main__:main"
